[GLOBAL_PRAGMA]
grflangid = "0x5a"
plural = "1"

[STR_GRF_DESCRIPTION]
base = "Lisensi: {SILVER}GPL v2{}{BLACK}"

[STR_EMPTY]
base = ""

[STR_PARAM_RESET_CONSTRUCTION_COSTS]
base = "Pakai Harga infrakstruktur kanal yang baru"

[STR_PARAM_RESET_CONSTRUCTION_COSTS_DESC]
base = "Memberi Harga yang seimbang untuk infrakstruktur kanal"

[STR_PARAM_ADJUST_SHIP_SPEEDS]
base = "Kecepatan Kapal"

[STR_PARAM_ADJUST_SHIP_SPEEDS_OPTION_0]
base = "Seperti Melihat cat mengering"

[STR_PARAM_ADJUST_SHIP_SPEEDS_OPTION_1]
base = "Seimbang"

[STR_PARAM_ADJUST_SHIP_SPEEDS_OPTION_2]
base = "Curang"

[STR_PARAM_ROSTER]
base = "Roster"

[STR_PARAM_ROSTER_DESC]
base = "Pilih set yang akan dipakai."

[STR_PARAM_ROSTER_OPTION_0]
base = "Pulau Sceptered ini"

[STR_NAME_BULK_BARGE]
base = "Tongkang Masal"

[STR_NAME_CARGO_LINER]
base = "Kapal Kargo"

[STR_NAME_COLLIER]
base = "Kapal Pengangkut Batubara"

[STR_NAME_COVERED_HOPPER_BARGE]
base = "Tongkang Masal tertutup"

[STR_NAME_CRYO_TANKER]
base = "Kapal Tanker Gas"

[STR_NAME_EDIBLES_TANKER]
base = "Kapal Tanker Makanan"

[STR_NAME_FREIGHTER_BARGE]
base = "Tongkang"

[STR_NAME_FREIGHTER_SHIP]
base = "Kapal barang"

[STR_NAME_LIVESTOCK_CARRIER]
base = "Kapal Pengangkut ternak"

[STR_NAME_LOG_TUG]
base = "Log Tug"

[STR_NAME_MAIL_SHIP]
base = "Kapal Surat"

[STR_NAME_MINI_BULKER]
base = "Bulker mini"

[STR_NAME_PAX_FAST_LOADING]
base = "Ferri"

[STR_NAME_PAX_LUXURY]
base = "Ferri Mewah"

[STR_NAME_REEFER]
base = "Kapal Pendingin"

[STR_NAME_TANKER_BARGE]
base = "Tongkang Tanker"

[STR_NAME_TANKER_SHIP]
base = "Tanker"

[STR_NAME_TRAWLER]
base = "Kapal Pemukat"

[STR_NAME_UTILITY_HOVERCRAFT]
base = "Hovercraft"

[STR_POWER_TYPE_DIESEL]
base = "Diesel"

[STR_HULL_SIZE_A]
base = "Micro"

[STR_HULL_SIZE_B]
base = "Mini"

[STR_HULL_SIZE_C]
base = "Kecil"

[STR_HULL_SIZE_D]
base = "Besar"

[STR_BUY_MENU_TEXT]
base = "{}Tipe: {GOLD}{STRING}{}{STRING}"

[STR_BUY_MENU_REFIT_CAPACITIES_PACKET]
base = "{}{BLACK}Kapapitas Ketika di Isi ulang: {GOLD}{COMMA} Kantong Surat atay {COMMA}ton kargo exspress"

[STR_GENERIC_REFIT_SUBTYPE]
base = "({COMMA} units)"

[STR_GENERIC_REFIT_SUBTYPE_BUY_MENU_INFO]
base = "{}{BLACK}Kapasitas yang dapat diisi ulang: {GOLD}{COMMA}, {COMMA} atau {COMMA}{STRING}"

[STR_SPRITES_COMPLETE]
base = "{}Sprite Lengkap: {GOLD}Yup"

[STR_SPRITES_INCOMPLETE]
base = "{}Sprite Lengkap: {GOLD}Tidak"
